spring:
  jpa:
    database: "MYSQL"
    show-sql: "false"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
  datasource:
    url: "jdbc:mysql://localhost/rsmortgage"
    platform: "mysql"
    username: "root"
    password: "root"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
    